#+TITLE: Emacs Literate Configuration
#+AUTHOR:  Eric Miller
#+PROPERTY: header-args :tangle yes

* Introduction
:PROPERTIES:
:VISIBILITY: children
:END:

** Table of Contents :TOC_3_gh:
- [[#introduction][Introduction]]
  - [[#about-this-file][About this file]]
  - [[#org-file-tweaks][Org File Tweaks]]
    - [[#automatically-tangle][Automatically Tangle]]
    - [[#visibility-settings][Visibility Settings]]
    - [[#table-of-contents][Table of Contents]]
  - [[#personal-information][Personal Information]]
- [[#emacs-initialization][Emacs Initialization]]
  - [[#settings][Settings]]
  - [[#integrate-with-use-package][Integrate with use-package]]
- [[#configure-nano][Configure nano]]
  - [[#install-nano-and-its-dependencies][Install nano and its dependencies]]
  - [[#setup-fonts][Setup fonts]]
  - [[#load-the-nano-layout][Load the nano layout]]
  - [[#set-up-nano-font-faces][Set up nano font faces]]
  - [[#set-up-the-nano-theme][Set up the nano theme]]
  - [[#load-nano-defaults][Load nano defaults]]
  - [[#enable-nano-session-handling][Enable nano session handling]]
  - [[#enable-the-nano-modeline][Enable the nano modeline]]
  - [[#enable-dark-theme][Enable dark theme]]
- [[#display][Display]]
  - [[#whitespace][Whitespace]]
- [[#wordsmithing][Wordsmithing]]
  - [[#configure-text-encoding][Configure text encoding]]
  - [[#hippie-expand][Hippie expand]]
  - [[#flyspell][Flyspell]]
  - [[#dictionary][Dictionary]]
  - [[#fill-mode][Fill mode]]
- [[#completion-frameworks][Completion Frameworks]]
  - [[#vertico][Vertico]]
  - [[#marginalia][Marginalia]]
  - [[#consult][Consult]]
- [[#eshell][EShell]]
- [[#git][Git]]
  - [[#enable-git-gutter-fringe][Enable git-gutter-fringe]]
  - [[#git-configuration-file-mode][git configuration file mode]]
  - [[#git-blame-in-a-buffer][git blame in a buffer]]
  - [[#magit][Magit]]
- [[#programming][Programming]]
  - [[#eldoc][ElDoc]]
- [[#org-mode][Org mode]]
  - [[#toc-org][Toc-org]]
- [[#misc-helpful-settings][Misc helpful settings]]
  - [[#which-key][Which-key]]
  - [[#auto-revert-mode][Auto-revert mode]]
- [[#post-initialization][Post Initialization]]

** About this file
This is an Emacs literate configuration template. It contains the basic structure
of a literate config along with some optimizations to ensure a fast load time.

I started with the files authored by Andrés Ejmson and titled [[https://github.com/frap/emacs-literate][Atea Emacs
Literate Configuration]].  This version has been almost complete rebuilt
with the move to using nano-emacs

** Org File Tweaks
There are a few tweaks included in this org file that make it a little easier to
work with.

*** Automatically Tangle
First there is a property defined on the file:

#+begin_src :tangle no
header-args :tangle yes
#+end_src

This tells emacs to automatically tangle (include) all code blocks in
this file when generating the code for the config, unless the code
block explicitly includes =:tangle no= as the above code block does.

*** Visibility Settings
Next we have a property defined on the [[Configuration][Configuration]] heading that
defines the visibility that tells org to show it's direct children on
startup. This way a clean outline of all sub headings under
Configuration is shown each time this file is opened in org-mode.

*** Table of Contents
Finally, there is a [[Table of Contents][Table of Contents]] heading that includes the tag:
=:TOC_3_gh:=. This tells an org-mode package =toc-org= to generate a table
of contents under this heading that has a max depth of 3 and is
created using Github-style hrefs. This table of contents is updated
everytime the file is saved and makes for a functional table of
contents that works property directly on github.

** Personal Information
Let's set some variables with basic user information.

#+begin_src emacs-lisp
(setq user-full-name "Eric Miller"
      user-mail-address "eric@gwonk.com")
#+end_src

* Emacs Initialization

** Settings
We're going to increase the gc-cons-threshold to a very high number to
decrease the load and compile time.  We'll lower this value
significantly after initialization has completed. We don't want to
keep this value too high or it will result in long GC pauses during
normal usage.

#+begin_src emacs-lisp
(eval-and-compile
  (setq gc-cons-threshold 402653184
        gc-cons-percentage 0.6))
#+end_src

Disable certain byte compiler warnings to cut down on the noise. This
is a personal choice and can be removed if you would like to see any
and all byte compiler warnings.

#+begin_src emacs-lisp
  (setq byte-compile-warnings
        '(not free-vars unresolved noruntime lexical make-local))
#+end_src

** Integrate with use-package

#+begin_src emacs-lisp
  (straight-use-package 'use-package)

  (use-package straight
    :custom
    (straight-use-package-by-default t))
#+end_src

* Configure nano

** Install nano and its dependencies

#+begin_src emacs-lisp
  (straight-use-package
   '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))
#+end_src

** Setup fonts

#+begin_src emacs-lisp
  (setq nano-font-family-monospaced "Input Mono Narrow")
  (setq nano-font-family-proportional nil)
  (setq nano-font-size 14)
  ;(set-frame-font "Input Mono Narrow-14")
#+end_src

** Load the nano layout

#+begin_src emacs-lisp
  (require 'nano-layout)
#+end_src

** Set up nano font faces

#+begin_src emacs-lisp
  (require 'nano-faces)
  (nano-faces)
#+end_src

** Set up the nano theme

#+begin_src emacs-lisp
  (require 'nano-theme)
  (nano-theme)
#+end_src

** Load nano defaults

#+begin_src emacs-lisp
  (require 'nano-defaults)
#+end_src

** Enable nano session handling

#+begin_src emacs-lisp
  (require 'nano-session)
#+end_src

** Enable the nano modeline

#+begin_src emacs-lisp
  (require 'nano-modeline)
#+end_src

** Enable dark theme

#+begin_src emacs-lisp
  (require 'nano-theme-dark)
  (nano-theme-set-dark)
  (call-interactively 'nano-refresh-theme)
#+end_src

* Display

** Whitespace

Don't use tab characters and indent 4 chars

#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 4)
#+end_src

Require a newline at the end of file

#+begin_src emacs-lisp
  (setq require-final-newline t)
#+end_src

Delete selection

#+begin_src emacs-lisp
(delete-selection-mode t)
#+end_src

Highlight whitespace in buffer

#+begin_src emacs-lisp
  (use-package whitespace
    :bind ("C-c T w" . whitespace-mode)
    :delight " 🗒️"
    :init
     (setq whitespace-line-column nil
            whitespace-display-mappings '((space-mark 32 [183] [46])
                                             (newline-mark 10 [9166 10])
                                             (tab-mark 9 [9654 9] [92 9])))
    ;(dolist (hook '(prog-mode-hook text-mode-hook))
    ;  (add-hook hook #'whitespace-mode))
    (add-hook 'before-save-hook #'whitespace-cleanup)
    :config
    (setq whitespace-line-column 80) ;; limit line length
    (setq whitespace-style '(face tabs empty trailing lines-tail))
    (set-face-attribute 'whitespace-space       nil :foreground "#666666" :background nil)
    (set-face-attribute 'whitespace-newline     nil :foreground "#666666" :background nil)
    (set-face-attribute 'whitespace-indentation nil :foreground "#666666" :background nil)
  )
#+end_src

* Wordsmithing

Text editing options

** Configure text encoding

#+begin_src emacs-lisp
  (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
#+end_src

** Hippie expand

#+begin_src emacs-lisp
  (setq hippie-expand-try-functions-list '(try-expand-dabbrev
                                           try-expand-dabbrev-all-buffers
                                           try-expand-dabbrev-from-kill
                                           try-complete-file-name-partially
                                           try-complete-file-name
                                           try-expand-all-abbrevs
                                           try-expand-list
                                           try-expand-line
                                           try-complete-lisp-symbol-partially
                                           try-complete-lisp-symbol))

  ;; use hippie-expand instead of dabbrev
  (global-set-key (kbd "M-/") #'hippie-expand)
  (global-set-key (kbd "s-/") #'hippie-expand)
#+end_src

** Flyspell

#+begin_src emacs-lisp
  (use-package flyspell
    :config
      (when (eq system-type 'windows-nt)
        (add-to-list 'exec-path "C:/Program Files (x86)/Aspell/bin/"))
      (setq ispell-program-name "aspell" ; use aspell instead of ispell
           ispell-extra-args '("--sug-mode=ultra"))
      (add-hook 'text-mode-hook #'flyspell-mode)
      (add-hook 'prog-mode-hook #'flyspell-prog-mode)
    :delight "")
#+end_src

** Dictionary

As suggested in [[https://irreal.org/blog/?p=10824][Webster 1913 and dictionary.el]]

#+begin_src emacs-lisp
  (setq dictionary-server "dict.org")
#+end_src

** Fill mode

Automatically wrap text.

#+begin_src emacs-lisp
  (use-package emacs
      :bind (("C-c T f" . auto-fill-mode)
             ("C-c T t" . toggle-truncate-lines))
      :init (add-hook 'org-mode-hook 'turn-on-auto-fill)
      :diminish auto-fill-mode)
#+end_src

* Completion Frameworks

** Vertico

#+begin_src emacs-lisp
  ;; Enable vertico
  (use-package vertico
    :init
    (vertico-mode)

    ;; Different scroll margin
    ;; (setq vertico-scroll-margin 0)

    ;; Show more candidates
    ;; (setq vertico-count 20)

    ;; Grow and shrink the Vertico minibuffer
    ;; (setq vertico-resize t)

    ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
    ;; (setq vertico-cycle t)
    )

  ;; Optionally use the `orderless' completion style. See
  ;; `+orderless-dispatch' in the Consult wiki for an advanced Orderless style
  ;; dispatcher. Additionally enable `partial-completion' for file path
  ;; expansion. `partial-completion' is important for wildcard support.
  ;; Multiple files can be opened at once with `find-file' if you enter a
  ;; wildcard. You may also give the `initials' completion style a try.
  (use-package orderless
    :init
    ;; Configure a custom style dispatcher (see the Consult wiki)
    ;; (setq orderless-style-dispatchers '(+orderless-dispatch)
    ;;       orderless-component-separator #'orderless-escapable-split-on-space)
    (setq completion-styles '(orderless)
          completion-category-defaults nil
          completion-category-overrides '((file (styles partial-completion)))))

  ;; Persist history over Emacs restarts. Vertico sorts by history position.
  (use-package savehist
    :init
    (savehist-mode))
#+end_src

** Marginalia

#+begin_src emacs-lisp
  ;; Enable richer annotations using the Marginalia package
  (use-package marginalia
    ;; Either bind `marginalia-cycle` globally or only in the minibuffer
    :bind (("M-A" . marginalia-cycle)
           :map minibuffer-local-map
           ("M-A" . marginalia-cycle))

    ;; The :init configuration is always executed (Not lazy!)
    :init

    ;; Must be in the :init section of use-package such that the mode gets
    ;; enabled right away. Note that this forces loading the package.
    (marginalia-mode))
#+end_src

** Consult

#+begin_src emacs-lisp
  ;; Example configuration for Consult
  (use-package consult
    ;; Replace bindings. Lazily loaded due by `use-package'.
    :bind (;; C-c bindings (mode-specific-map)
           ("C-c h" . consult-history)
           ("C-c m" . consult-mode-command)
           ("C-c b" . consult-bookmark)
           ("C-c k" . consult-kmacro)
           ;; C-x bindings (ctl-x-map)
           ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
           ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
           ("C-x C-b" . consult-buffer)                ;; orig. switch-to-buffer
           ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
           ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
           ;; Custom M-# bindings for fast register access
           ("M-#" . consult-register-load)
           ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
           ("C-M-#" . consult-register)
           ;; Other custom bindings
           ("M-y" . consult-yank-pop)                ;; orig. yank-pop
           ("<help> a" . consult-apropos)            ;; orig. apropos-command
           ;; M-g bindings (goto-map)
           ("M-g e" . consult-compile-error)
           ("M-g f" . consult-flycheck)               ;; Alternative: consult-flymake
           ("M-g g" . consult-goto-line)             ;; orig. goto-line
           ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
           ("M-g o" . consult-org-heading)               ;; Alternative: consult-outline
           ("M-g a" . consult-org-agenda)

           ("M-g m" . consult-mark)
           ("M-g k" . consult-global-mark)
           ("M-g i" . consult-imenu)
           ("M-g I" . consult-imenu-multi)
           ;; M-s bindings (search-map)
           ("M-s f" . consult-find)
           ("M-s F" . consult-locate)
           ("M-s g" . consult-grep)
           ("M-s G" . consult-git-grep)
           ("M-s r" . consult-ripgrep)
           ("M-s l" . consult-line)
           ("M-s L" . consult-line-multi)
           ("M-s m" . consult-multi-occur)
           ("M-s k" . consult-keep-lines)
           ("M-s u" . consult-focus-lines)
           ;; Isearch integration
           ("M-s e" . consult-isearch-history)
           :map isearch-mode-map
           ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
           ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
           ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
           ("M-s L" . consult-line-multi))           ;; needed by consult-line to detect isearch

    ;; Enable automatic preview at point in the *Completions* buffer. This is
    ;; relevant when you use the default completion UI. You may want to also
    ;; enable `consult-preview-at-point-mode` in Embark Collect buffers.
    :hook (completion-list-mode . consult-preview-at-point-mode)

    ;; The :init configuration is always executed (Not lazy)
    :init

    ;; Optionally configure the register formatting. This improves the register
    ;; preview for `consult-register', `consult-register-load',
    ;; `consult-register-store' and the Emacs built-ins.
    (setq register-preview-delay 0
          register-preview-function #'consult-register-format)

    ;; Optionally tweak the register preview window.
    ;; This adds thin lines, sorting and hides the mode line of the window.
    (advice-add #'register-preview :override #'consult-register-window)

    ;; Optionally replace `completing-read-multiple' with an enhanced version.
    (advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)

    ;; Use Consult to select xref locations with preview
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)

    ;; Configure other variables and modes in the :config section,
    ;; after lazily loading the package.
    :config

    ;; Optionally configure preview. The default value
    ;; is 'any, such that any key triggers the preview.
    ;; (setq consult-preview-key 'any)
    ;; (setq consult-preview-key (kbd "M-."))
    ;; (setq consult-preview-key (list (kbd "<S-down>") (kbd "<S-up>")))
    ;; For some commands and buffer sources it is useful to configure the
    ;; :preview-key on a per-command basis using the `consult-customize' macro.
    (consult-customize
     consult-theme
     :preview-key '(:debounce 0.2 any)
     consult-ripgrep consult-git-grep consult-grep
     consult-bookmark consult-recent-file consult-xref
     consult--source-recent-file consult--source-project-recent-file consult--source-bookmark
     :preview-key (kbd "M-."))

    ;; Optionally configure the narrowing key.
    ;; Both < and C-+ work reasonably well.
    (setq consult-narrow-key "<") ;; (kbd "C-+")

    ;; Optionally make narrowing help available in the minibuffer.
    ;; You may want to use `embark-prefix-help-command' or which-key instead.
    ;; (define-key consult-narrow-map (vconcat consult-narrow-key "?") #'consult-narrow-help)

    ;; Optionally configure a function which returns the project root directory.
    ;; There are multiple reasonable alternatives to chose from.
    ;;;; 1. project.el (project-roots)
    (setq consult-project-root-function
          (lambda ()
            (when-let (project (project-current))
              (car (project-roots project)))))
    ;;;; 2. projectile.el (projectile-project-root)
    ;; (autoload 'projectile-project-root "projectile")
    ;; (setq consult-project-root-function #'projectile-project-root)
    ;;;; 3. vc.el (vc-root-dir)
    ;; (setq consult-project-root-function #'vc-root-dir)
    ;;;; 4. locate-dominating-file
    ;; (setq consult-project-root-function (lambda () (locate-dominating-file "." ".git")))
    )
  (use-package consult-flycheck
    :ensure t)
#+end_src

* EShell

Start the eshell and bind f12 to the swap function.

#+begin_src emacs-lisp
  (use-package eshell
    :ensure t
    :config
    (defvar ejm-save-buffer "*scratch*"
      "Stores the return buffer for the ejm-shell command.")
    (defun ejm-shell()
      "Switch to the eshell window or return to previous"
      (interactive)
      (cond ((equal (buffer-name) "*eshell*")
             (switch-to-buffer ejm-saved-buffer))
            (t
             (setq ejm-saved-buffer (buffer-name))
             (switch-to-buffer "*eshell*"))))
    :init
    (eshell)
    (global-set-key [f12] 'ejm-shell))
#+end_src

* Git

** Enable git-gutter-fringe

#+begin_src emacs-lisp
  (use-package git-gutter-fringe
    :ensure t
    :init (setq git-gutter-fr:side 'right-fringe)
    :config (global-git-gutter-mode t))
#+end_src

** git configuration file mode

#+begin_src emacs-lisp
  (use-package git-modes
    :ensure t)
#+end_src

** git blame in a buffer

Run mo-git-blame-current

#+begin_src emacs-lisp :tangle no
  (use-package mo-git-blame
    :ensure t)
#+end_src

** Magit

#+begin_src emacs-lisp
  (use-package magit
    :ensure t
    :commands magit-status magit-blame magit-section
    :init
    (defadvice magit-status (around magit-fullscreen activate)
      (window-configuration-to-register :magit-fullscreen)
      ad-do-it
      (delete-other-windows))
    :config
    (setq magit-branch-arguments nil
          ;; use ido to look for branches
          magit-completing-read-function 'magit-ido-completing-read
          ;; don't put "origin-" in front of new branch names by default
          magit-default-tracking-name-function 'magit-default-tracking-name-branch-only
          magit-push-always-verify nil
          ;; Get rid of the previous advice to go into fullscreen
          magit-restore-window-configuration t)

    :bind ("C-x g" . magit-status))

#+end_src
* Programming

** ElDoc

#+begin_src emacs-lisp
  (use-package eldoc
    :defer t)
#+end_src

* Org mode

** Toc-org

#+begin_src emacs-lisp
  (use-package toc-org
    :after org
    :init (add-hook 'org-mode-hook #'toc-org-enable))
#+end_src


* Misc helpful settings

** Which-key

#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :init
    (which-key-mode +1))
#+end_src

** Auto-revert mode

Revert buffers automatically when the underlying files change.

#+begin_src emacs-lisp
  (global-auto-revert-mode t)
#+end_src

* Post Initialization

Reset GC thresholds to more reasonable numbers.

#+begin_src emacs-lisp
  (setq gc-cons-threshold 16777216
        gc-cons-percentage 0.1)
#+end_src
